package com.lyl.model;

import java.io.Serializable;

public class Manager implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerId
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    private Integer managerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerName
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    private String managername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerPassword
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    private String managerpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerId
     *
     * @return the value of manager.managerId
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerId
     *
     * @param managerid the value for manager.managerId
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerName
     *
     * @return the value of manager.managerName
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerName
     *
     * @param managername the value for manager.managerName
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    public void setManagername(String managername) {
        this.managername = managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerPassword
     *
     * @return the value of manager.managerPassword
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    public String getManagerpassword() {
        return managerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerPassword
     *
     * @param managerpassword the value for manager.managerPassword
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    public void setManagerpassword(String managerpassword) {
        this.managerpassword = managerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Manager other = (Manager) that;
        return (this.getManagerid() == null ? other.getManagerid() == null : this.getManagerid().equals(other.getManagerid()))
            && (this.getManagername() == null ? other.getManagername() == null : this.getManagername().equals(other.getManagername()))
            && (this.getManagerpassword() == null ? other.getManagerpassword() == null : this.getManagerpassword().equals(other.getManagerpassword()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getManagerid() == null) ? 0 : getManagerid().hashCode());
        result = prime * result + ((getManagername() == null) ? 0 : getManagername().hashCode());
        result = prime * result + ((getManagerpassword() == null) ? 0 : getManagerpassword().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", managerid=").append(managerid);
        sb.append(", managername=").append(managername);
        sb.append(", managerpassword=").append(managerpassword);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}