package com.lyl.mapper;

import com.lyl.model.Manager;
import java.util.List;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    int deleteByPrimaryKey(Integer managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    Manager selectByPrimaryKey(Integer managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    List<Manager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated Fri Sep 30 11:43:28 CST 2016
     */
    int updateByPrimaryKey(Manager record);
}